# kubernetes deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: wait-for-redis
          image: redis:7.2
          command:
            - sh
            - -c
            - redis-cli -h my-redis ping

        - name: wait-for-postgres
          image: postgres:15
          command:
            - sh
            - -c
            - pg_isready -h db -U test_user -d test_db
      containers:
        - name: backend
          image: "${TESTING_IMAGE}"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: backend-secrets
          env:
            - name: REDIS_HOST
              value: "my-redis"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 3
            failureThreshold: 5
