FROM ubuntu:jammy

# Using curl to get node 18 version
RUN apt update \
  && apt install -y curl ca-certificates gnupg \
  && curl -sL https://deb.nodesource.com/setup_18.x | bash - \
  && apt-get install nodejs -y

COPY . .

RUN npm install

CMD ["npm", "run", "dev"]
