FROM node:22.16.0-bullseye-slim AS base

WORKDIR /usr/src/app

COPY package*.json ./
COPY .sequelizerc ./


FROM base AS test

ENV NODE_ENV=test
ENV TEST_DATABASE_URL=postgres://test_user:test_password@db:5432/test_db

RUN --mount=type=cache,target=/usr/src/app/.npm \
  npm set cache /usr/src/app/.npm && \
  npm install

RUN apt-get update && \
    apt-get install -y curl

COPY ./src/ ./src/
COPY ./test/ ./test/

EXPOSE 3000

CMD ["npm", "run", "dev"]

FROM base AS production

ENV NODE_ENV=production

RUN --mount=type=cache,target=/usr/src/app/.npm \
  npm set cache /usr/src/app/.npm && \
  npm ci --only=production

USER node

COPY --chown=node:node ./src/ ./src/

EXPOSE 3000

CMD [ "node", "index.js" ]