# Pin specific version for stability
# Use slim for reduced image size
FROM node:22.16.0-bullseye-slim

# Specify working directory other than /
WORKDIR /usr/src/app

# Copy only files required to install
# dependencies (better layer caching)
COPY package*.json ./
COPY .sequelizerc ./

RUN npm install

# Copy remaining source code AFTER installing dependencies. 
# Again, copy only the necessary files
COPY ./src/ ./src/

CMD [ "node", "index.js" ]
